apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tpm-tools-backend.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          env:
            - name: DB_CONNECTION_STRING
              value: jdbc:mysql://$(TPM_TOOLS_DB_SERVICE_SERVICE_HOST):3306/tpm-tools
            - name: DB_USER
              value: local-user
            - name: DB_PASSWORD
              value: pwd2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

