apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tpm-tools-backend.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tpm-tools-backend.fullname" . }}-service
                port:
                  # name: http
                  number: {{.Values.service.port}}

