apiVersion: v1
kind: Service
metadata:
  name: {{ include "tpm-tools-backend.fullname" . }}-service
  labels:
    app: tpm-tools-backend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{.Chart.Name}}