apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ include "grafana.fullname" . }}
spec:
  selector:
    matchLabels:
      app: grafana
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: grafana
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: {{ .Chart.Name }}
          image: grafana/grafana:9.1.0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-grafana
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.service.port }}
            timeoutSeconds: 1

      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
