apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tpm-tools-db.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: {{ .Chart.Name }}-data-storage
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pwd
            - name: MYSQL_DATABASE
              value: tpm-tools
            - name: MYSQL_USER
              value: local-user
            - name: MYSQL_PASSWORD
              value: pwd2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Chart.Name }}-data-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-persistent-volume-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
