apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-persistent-volume
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: {{ .Chart.Name }}-persistent-volume-claim
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/chrisatkins/workspace/k8s/persistent-volume"
