CREATE TABLE P0_PROJECT_PLAN (
    ID int NOT NULL AUTO_INCREMENT,
    TITLE varchar(255) NULL,

    PRIMARY KEY (ID)
);

INSERT INTO P0_PROJECT_PLAN (TITLE)
    VALUE ("First Project Plan");

ALTER TABLE P1_ROW
    ADD COLUMN P0_PROJECT_PLAN_FK int NOT NULL DEFAULT 1 AFTER ID;

ALTER TABLE P1_ROW
ADD FOREIGN KEY (P0_PROJECT_PLAN_FK) REFERENCES P0_PROJECT_PLAN(ID);

ALTER TABLE P1_ROW
    ALTER COLUMN P0_PROJECT_PLAN_FK DROP DEFAULT;